# Generated by Django 3.2.22 on 2023-12-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commit',
            new_name='comment',
        ),
    ]
