# Generated by Django 3.2.22 on 2023-12-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0004_rename_commit_comment_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
