# Generated by Django 4.2.3 on 2024-01-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0007_alter_blog_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='blog_id',
        ),
    ]
