# Generated by Django 4.2.3 on 2024-01-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0009_rename_comment_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
